#PORT
server:
  port: 8082

spring:
  #RabbitMQ AND QUEUE CONFIGURATION
  activemq:
    broker-url: tcp://127.0.0.1:5672
  rabbitmq:
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: codjavando-stream

